on:
    push

jobs:
    run-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7 

            - name: Run 'leetcode-submit'
              uses: romeosarkar10x-gh-action/leetcode-submit@v0.0.0-alpha-775bceecc80c28fc99f40e786b12bb33354eb06c
              with:
                  leetcode-session-cookie: MY_COOKIE
                  manifest-file: .leetcode.json


